const abroadJobs = [
  {
    title: "Delivery Rider",
    country: "Kuwait",
    category: "Delivery",
    salary: "300 KWD",
    incentive: "Available",
    description: "",
  },
  {
    title: "Delivery Rider",
    country: "Dubai",
    category: "Delivery",
    salary: "4000 - 5500 AED",
    incentive: "Available",
    description: "",
  },

  {
    title: "Helper",
    country: "UAE",
    category: "Labor/Helper",
    salary: "1200 AED",
    incentive: " No Available",
    description: "",
  },

  {
    title: "Spray Painter",
    country: "UAE",
    category: "Labor/Helper",
    salary: "1600 AED",
    incentive: "No Available",
    description: "",
  },
  {
    title: "Painter",
    country: "UAE",
    category: "Labor/Helper",
    salary: "1300 AED",
    incentive: "No Available",
    description: "",
  },
  {
    title: "Carpenter",
    country: "UAE",
    category: "Carpenter",
    salary: "1600 AED",
    incentive: "No Available",
    description: "",
  },
  {
    title: "Steel Fixer",
    country: "UAE",
    category: "Labor/Helper",
    salary: "1300 AED",
    incentive: "No Available",
    description: "",
  },
  {
    title: "Scaffolder",
    country: "UAE",
    category: "Labor/Helper",
    salary: "1300 AED",
    incentive: "No Available",
    description: "",
  },
  {
    title: "Rigger",
    country: "UAE",
    category: "Labor/Helper",
    salary: "1300 AED",
    incentive: "No Available",
    description: "",
  },

  {
    title: "General Laborer",
    country: "Oman",
    category: "Labor/Helper",
    salary: "140 OMR",
    incentive: "No Available",
    description: "",
  },
  {
    title: "Mason (construction Worker)",
    country: "Oman",
    category: "Labor/Helper",
    salary: "180 - 200 OMR",
    incentive: "No Available",
    description: "",
  },
  {
    title: "Helper",
    country: "Oman",
    category: "Labor/Helper",
    salary: "120 - 125 OMR",
    incentive: "No Available",
    description: "",
  },

  {
    title: "Shuttering Carpenter",
    country: "Oman",
    category: "Labor/Helper",
    salary: "180 - 200 OMR",
    incentive: "No Available",
    description: "",
  },
];

export default abroadJobs;
