export const JOBS_LIST = [
  {
    id: 1,
    title: "Construction Helper",
    location: "Abroad / UAE & Dubai",
    type: "Full Time",
  },
  {
    id: 2,
    title: "Block Mason",
    location: "Abroad / UAE & Dubai",
    type: "Full Time",
  },
  {
    id: 3,
    title: "Bike Rider",
    location: "Abroad / UAE & Dubai",
    type: "Full Time",
  },
  {
    id: 4,
    title: "Cyclist",
    location: "Abroad / UAE & Dubai",
    type: "Full Time",
  },
  {
    id: 5,
    title: "Warehouse Picker",
    location: "Abroad / UAE & Dubai",
    type: "Full Time",
  },
  {
    id: 6,
    title: "HVAC Technician",
    location: "Abroad / UAE & Dubai",
    type: "Full Time",
  },
  {
    id: 7,
    title: "Electrician",
    location: "Abroad / UAE & Dubai",
    type: "Full Time",
  },
  {
    id: 8,
    title: "Plumber",
    location: "Abroad / UAE & Dubai",
    type: "Full Time",
  },
  {
    id: 9,
    title: "Pipe Fitters",
    location: "Abroad / UAE & Dubai",
    type: "Full Time",
  },
  {
    id: 10,
    title: "Security Guards",
    location: "Abroad / UAE & Dubai",
    type: "Full Time",
  },
];

export const INDIAN_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Delhi NCR",
  "Jammu and Kashmir",
  "Ladakh",
  "Puducherry",
  "Chandigarh",
];

export const AGE_GROUPS = [
  "21 to 25 years",
  "26 to 30 years",
  "31 to 35 years",
  "36 to 40 years",
];
